"""empty message

Revision ID: 1db7b6b7ef1a
Revises: d6b3ae99463
Create Date: 2015-08-17 02:05:32.702365

"""

# revision identifiers, used by Alembic.
revision = '1db7b6b7ef1a'
down_revision = 'd6b3ae99463'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
