"""empty message

Revision ID: 50ec4a13963c
Revises: 1db7b6b7ef1a
Create Date: 2015-08-17 02:08:05.262838

"""

# revision identifiers, used by Alembic.
revision = '50ec4a13963c'
down_revision = '1db7b6b7ef1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('like', 'created_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('created_at', sa.DATETIME(), nullable=True))
    ### end Alembic commands ###
